watch:
	dotnet watch --project Samit.WebUi
run:
	dotnet run --project Samit.WebUi
publish:
	dotnet publish Samit.WebUi -c Release -o Samit.WebUi/bin/publish && cp -R Samit.WebUi/bin/publish/wwwroot/* ../../ 
